#CPPFLAGS += -DNDEBUG
CFLAGS += -std=gnu99

SRC_DIR = src
INC_DIR = include
OBJ_DIR = obj
LIB_DIR = lib
BIN_DIR = bin

VERSION=0.1

CALENDARMANAGER_NAME = ZigBeeSensor
CALENDARMANAGER_SRCS = BootStrap.cpp af.cpp FlashMng.cpp led.cpp mainComponent.cpp nwk.cpp sensor.cpp sys.cpp temperatureCluster.cpp temperatureSensor.cpp zigBeeStack.cpp
CALENDARMANAGER_CPPFLAGS =
CALENDARMANAGER_CFLAGS =
CALENDARMANAGER_LDFLAGS = -L./libs
CALENDARMANAGER_LIBS = -lFlashMngExt

BINARIES = ZigBeeSensor
ARCHIVES =
LIBRARIES =

include Makefile.auto
